/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import ModelDAO.DaoFuncionario;
import ModelDAO.DaoUsuario;
import java.awt.Color;
import java.awt.Cursor;
import Telas.*;
import javax.swing.JOptionPane;
/**
 *
 * @author anton
 */
public class Tela_Login extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Login
     */
    public Tela_Login() {
        initComponents();
        //Aqui eu seto o texto sublinhado e com italico usando comandos HTML
        Tela_Titulo_Label.setText("<html><b><i>Tela de Login</i></b></html>");
    }
// Método de logar
    
    public void Login(){
        try {
            // variável boolean que será o que verificará se teve ou não conexão
          
            // Capta os campos que serão verificados para realizar login
            
            String usuario = campo_Usuário.getText();
            String senha = campo_Senha.getText();
            
            DaoUsuario dao = new DaoUsuario(); // cria o objeto para acessar os métodos 
          
            if( dao.Login(usuario, senha)){   // seleciona o método que será realizado para verificar o login
                
                //se retornar true é por que os dados foram encontrados e abre o menu
                JOptionPane.showMessageDialog(null, "Login realizado com Sucesso");
            Tela_Menu menu = new Tela_Menu();
            menu.setVisible(true);
            this.dispose();
            
            
            }else{
             JOptionPane.showMessageDialog(null, "Login falhou, usuário ou senha errado"); // se der erro aparece essa mensagem
            
            }
            
        } catch (Exception e) {
        }
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tela_Titulo_Label = new javax.swing.JLabel();
        Tela_Aviso_Label = new javax.swing.JLabel();
        campo_Usuário = new javax.swing.JTextField();
        campo_Senha = new javax.swing.JPasswordField();
        label_User = new javax.swing.JLabel();
        label_senha = new javax.swing.JLabel();
        label_CadastroUser = new javax.swing.JLabel();
        bt_Acessar = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bem-Vindo Usuário");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tela_Titulo_Label.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        Tela_Titulo_Label.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(Tela_Titulo_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 500, 60));

        Tela_Aviso_Label.setFont(new java.awt.Font("Courier New", 1, 36)); // NOI18N
        Tela_Aviso_Label.setForeground(java.awt.Color.red);
        Tela_Aviso_Label.setText("<html><p style=text-shadow: \n" +
            "               -1px -1px 0px #FFF, \n" +
            "               -1px 1px 0px #FFF,      \n" +
            "                1px -1px 0px #FFF,    \n" +
            "                1px 0px 0px #FFF;> SOMENTE FUNCIONÁRIOS AUTORIZADOS</p></html>");
        getContentPane().add(Tela_Aviso_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, 720, 60));

        campo_Usuário.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        campo_Usuário.setForeground(new java.awt.Color(255, 255, 255));
        campo_Usuário.setCaretColor(new java.awt.Color(0, 0, 0));
        campo_Usuário.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        campo_Usuário.setBackground(Color.GRAY);
        getContentPane().add(campo_Usuário, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 280, 50));

        campo_Senha.setBackground(Color.GRAY);
        campo_Senha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        campo_Senha.setCaretColor(Color.WHITE);
        campo_Senha.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        getContentPane().add(campo_Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 368, 280, 50));

        label_User.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label_User.setForeground(new java.awt.Color(0, 0, 0));
        label_User.setText("Usuário");
        getContentPane().add(label_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        label_senha.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        label_senha.setForeground(new java.awt.Color(0, 0, 0));
        label_senha.setText("senha");
        getContentPane().add(label_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        label_CadastroUser.setForeground(new java.awt.Color(0, 51, 255));
        label_CadastroUser.setText("<html><i><u>Não possui Cadastro? Clique aqui</u></i></html>");
        label_CadastroUser.setCursor(new Cursor(Cursor.HAND_CURSOR));
        label_CadastroUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_CadastroUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                label_CadastroUserMouseEntered(evt);
            }
        });
        getContentPane().add(label_CadastroUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        bt_Acessar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        bt_Acessar.setText("Acessar");
        bt_Acessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AcessarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_Acessar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 170, 40));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void label_CadastroUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_CadastroUserMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_label_CadastroUserMouseEntered
//Método quue ao usuário clicar na label, ou seja clicar no texto, ele abre a tela de Cadastro
    private void label_CadastroUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_CadastroUserMouseClicked
       Tela_CadastroUsuário tela = new Tela_CadastroUsuário(); // instancia a  tela de cadastro
       tela.setVisible(true); //torna ela visivel
       this.dispose(); // fecha a tela de login para não ter duas telas abertas.
       
    }//GEN-LAST:event_label_CadastroUserMouseClicked

    private void bt_AcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AcessarActionPerformed
        if(campo_Usuário.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Preencha o campo de usuario");
        
        }else if(campo_Senha.getText().isEmpty()){
        JOptionPane.showMessageDialog(null, "Preencha o campo de senha");
        }else{
        Login();
        }
    }//GEN-LAST:event_bt_AcessarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Tela_Aviso_Label;
    private javax.swing.JLabel Tela_Titulo_Label;
    private javax.swing.JButton bt_Acessar;
    private javax.swing.JPasswordField campo_Senha;
    private javax.swing.JTextField campo_Usuário;
    private javax.swing.JLabel label_CadastroUser;
    private javax.swing.JLabel label_User;
    private javax.swing.JLabel label_senha;
    // End of variables declaration//GEN-END:variables
}
