/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import ModelBean.BeanFuncionario;
import ModelBean.BeanUsuario;
import ModelDAO.DaoFuncionario;
import ModelDAO.DaoUsuario;
import Telas.*;
import java.awt.Cursor;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author anton
 */
public class Tela_CadastroUsuário extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Tela_CadastroUsuário() {
        initComponents();
        /** Mudar o cursor do mouse pelos botões **/
        bt_limpar.setCursor(new Cursor(Cursor.HAND_CURSOR));
         bt_Salvar.setCursor(new Cursor(Cursor.HAND_CURSOR));
         label_voltarMenu.setCursor(new Cursor(Cursor.HAND_CURSOR));
         
         // O Texto de voltar ao menu
         label_voltarMenu.setText("<html><u>>>Clique para retornar ao Login<<</u></html>");
    }
      public void ListarFuncionario(){
        try {
            DaoFuncionario daofunc = new DaoFuncionario(); // criar o objeto com o metodo de listagem
            
            List<BeanFuncionario> listadefuncionarios = daofunc.ListadeFuncionario(); // criar a lista que recebe a lista do metodo
            
            // cria um objeto que recebe os valores pra setar na tabela
            
            DefaultTableModel table = (DefaultTableModel) tabela_Func.getModel();
            table.setNumRows(0);
            // cria o laço que joga os valores no objeto
            
            for(BeanFuncionario func : listadefuncionarios){ // cria um objeto  da classe bean que recebe os valores da lista
            table.addRow(new Object[]{ // adiciona uma lista no objeto para cada dado retornado da lista
            func.getCod_Func(), // insere as informações correspondentes em cada coluna
                func.getNome_Func(),
                func.getCpf_Func(),
               
            
            
            });
            
            
            }
        } catch (Exception e) {
        }
    
    }
    
 //Método de Cadastrar o Usuário
    
    public void CadastrarUsuario(){
    BeanUsuario beanuse = new BeanUsuario(); // cria objeto para acessar as variaveis
    
    //seta nas variaveis os valores dos campos
    
   beanuse.setNome_User(campo_nome_User.getText());
   beanuse.setSenha_User(campo_senha_User.getText());
   beanuse.setFk_cod_Func(Integer.parseInt(campo_Fk_Codfunc.getText()));
        
    DaoUsuario daouse = new DaoUsuario(); // cria objeto para acessar os metodos sql
    
    daouse.inserirDados(beanuse); // coloca o objeto bean para automaticamente ele usar os valores que foram setados 
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_Func = new javax.swing.JTable();
        label_senha_User = new javax.swing.JLabel();
        label_lista_Func = new javax.swing.JLabel();
        campo_Nome_Func = new javax.swing.JTextField();
        label_nome_Func = new javax.swing.JLabel();
        label_nome_User = new javax.swing.JLabel();
        campo_nome_User = new javax.swing.JTextField();
        bt_Salvar = new javax.swing.JButton();
        bt_limpar = new javax.swing.JButton();
        label_voltarMenu = new javax.swing.JLabel();
        campo_senha_User = new javax.swing.JPasswordField();
        background_CadastroUser = new javax.swing.JLabel();
        campo_Fk_Codfunc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Usuário");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela_Func.setBackground(new java.awt.Color(255, 255, 255));
        tabela_Func.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_Func.setOpaque(false);
        tabela_Func.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_FuncMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_Func);
        if (tabela_Func.getColumnModel().getColumnCount() > 0) {
            tabela_Func.getColumnModel().getColumn(0).setResizable(false);
            tabela_Func.getColumnModel().getColumn(1).setResizable(false);
            tabela_Func.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, 130));

        label_senha_User.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label_senha_User.setForeground(new java.awt.Color(0, 0, 0));
        label_senha_User.setText("Senha");
        getContentPane().add(label_senha_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, -1, -1));

        label_lista_Func.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label_lista_Func.setForeground(new java.awt.Color(0, 0, 0));
        label_lista_Func.setText("Lista de Funcionários");
        getContentPane().add(label_lista_Func, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));

        campo_Nome_Func.setBackground(new java.awt.Color(0, 0, 0));
        campo_Nome_Func.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        campo_Nome_Func.setEnabled(false);
        campo_Nome_Func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_Nome_FuncActionPerformed(evt);
            }
        });
        getContentPane().add(campo_Nome_Func, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 350, 40));

        label_nome_Func.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label_nome_Func.setForeground(new java.awt.Color(0, 0, 0));
        label_nome_Func.setText("Nome ");
        getContentPane().add(label_nome_Func, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        label_nome_User.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label_nome_User.setForeground(new java.awt.Color(0, 0, 0));
        label_nome_User.setText("Usuário");
        getContentPane().add(label_nome_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 90, -1));

        campo_nome_User.setBackground(new java.awt.Color(255, 255, 255));
        campo_nome_User.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        campo_nome_User.setForeground(new java.awt.Color(0, 0, 0));
        campo_nome_User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nome_UserActionPerformed(evt);
            }
        });
        getContentPane().add(campo_nome_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 350, 40));

        bt_Salvar.setBackground(new java.awt.Color(102, 255, 102));
        bt_Salvar.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        bt_Salvar.setForeground(new java.awt.Color(0, 0, 0));
        bt_Salvar.setText("Salvar");
        bt_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 170, 150, 60));

        bt_limpar.setBackground(new java.awt.Color(250, 66, 66));
        bt_limpar.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        bt_limpar.setForeground(new java.awt.Color(0, 0, 0));
        bt_limpar.setText("Limpar campos");
        bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparAção(evt);
            }
        });
        getContentPane().add(bt_limpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 110, 130, 30));

        label_voltarMenu.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        label_voltarMenu.setForeground(new java.awt.Color(0, 0, 255));
        label_voltarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_voltarMenuMouseClicked(evt);
            }
        });
        getContentPane().add(label_voltarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 350, 70));

        campo_senha_User.setBackground(new java.awt.Color(255, 255, 255));
        campo_senha_User.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        campo_senha_User.setToolTipText("");
        getContentPane().add(campo_senha_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, 250, 40));

        background_CadastroUser.setOpaque(true);
        getContentPane().add(background_CadastroUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -14, 1280, 740));

        campo_Fk_Codfunc.setText("jTextField1");
        getContentPane().add(campo_Fk_Codfunc, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void campo_Nome_FuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_Nome_FuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_Nome_FuncActionPerformed

    private void campo_nome_UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nome_UserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nome_UserActionPerformed

    private void label_voltarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_voltarMenuMouseClicked
        Tela_Login tela = new Tela_Login();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_label_voltarMenuMouseClicked

    private void bt_limparAção(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparAção
        campo_nome_User.setText(""); // os dois campos são apagados colocando nada 
        campo_senha_User.setText("");
        campo_Fk_Codfunc.setText("");
        
    }//GEN-LAST:event_bt_limparAção

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       ListarFuncionario();
    }//GEN-LAST:event_formWindowActivated

    private void bt_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SalvarActionPerformed
     if(campo_nome_User.getText().isEmpty()){
     JOptionPane.showMessageDialog(null, "Preencha o campo de usuario");
     }else if(campo_senha_User.getText().isEmpty()){
     JOptionPane.showMessageDialog(null, "Preencha o campo de senha");
     }else{
        
        try {
           CadastrarUsuario();
            campo_nome_User.setText("");
        campo_Nome_Func.setText("");
        campo_senha_User.setText("");
        campo_Fk_Codfunc.setText("");
     
            JOptionPane.showMessageDialog(null, "Cadastro realizado do usuário"); // se funcionar
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Cadastro falhou: erro "+e); // se der erro
        }
     }
    }//GEN-LAST:event_bt_SalvarActionPerformed

    private void tabela_FuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_FuncMouseClicked
      
        // Método que pega o valor da tabela e seta nos campos
        
        campo_Fk_Codfunc.setText(tabela_Func.getValueAt(tabela_Func.getSelectedRow(),0).toString());
        campo_Nome_Func.setText(tabela_Func.getValueAt(tabela_Func.getSelectedRow(), 1).toString());
    }//GEN-LAST:event_tabela_FuncMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_CadastroUsuário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_CadastroUsuário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_CadastroUsuário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_CadastroUsuário.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_CadastroUsuário().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_CadastroUser;
    private javax.swing.JButton bt_Salvar;
    private javax.swing.JButton bt_limpar;
    private javax.swing.JTextField campo_Fk_Codfunc;
    private javax.swing.JTextField campo_Nome_Func;
    private javax.swing.JTextField campo_nome_User;
    private javax.swing.JPasswordField campo_senha_User;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_lista_Func;
    private javax.swing.JLabel label_nome_Func;
    private javax.swing.JLabel label_nome_User;
    private javax.swing.JLabel label_senha_User;
    private javax.swing.JLabel label_voltarMenu;
    private javax.swing.JTable tabela_Func;
    // End of variables declaration//GEN-END:variables
}
